import { useState } from 'react'
import SalarySlip from './SalarySlip'
const initial = [{ id: 'EMP-1042', employee: 'Aarav Sharma', basic: 45000, allowances: 10500, deductions: 3300 }, { id: 'EMP-1051', employee: 'Priya Nair', basic: 52000, allowances: 12000, deductions: 4400 }, { id: 'EMP-1068', employee: 'Rohan Mehta', basic: 38000, allowances: 8000, deductions: 2800 }]
const money = (number) => `₹${Number(number).toLocaleString('en-IN')}`
export default function AdminPayroll() {
  const [employees, setEmployees] = useState(initial); const [selectedId, setSelectedId] = useState(initial[0].id)
  const selected = employees.find((employee) => employee.id === selectedId)
  const update = (field, value) => setEmployees((items) => items.map((employee) => employee.id === selectedId ? { ...employee, [field]: Math.max(0, Number(value) || 0) } : employee))
  return <main className="demo-content payroll-page"><section className="page-title"><div><p>PAYROLL / ADMIN</p><h1>Employee salary</h1><span>Add or update salary information. Net pay is calculated automatically.</span></div></section><section className="two-column admin-payroll"><section className="panel"><div className="panel-heading"><h2>Employees</h2><span>{employees.length} records</span></div><div className="employee-list">{employees.map((employee) => <button onClick={() => setSelectedId(employee.id)} className={employee.id === selectedId ? 'employee-row selected' : 'employee-row'} key={employee.id}><span className="employee-initial">{employee.employee[0]}</span><span>{employee.employee}<small>{employee.id}</small></span><b>{money(employee.basic + employee.allowances - employee.deductions)}</b></button>)}</div></section><section><section className="panel salary-form"><div className="panel-heading"><div><h2>Salary details</h2><span>{selected.employee} · {selected.id}</span></div><span className="status-pill">Active</span></div><label>Basic salary<input type="number" value={selected.basic} min="0" onChange={(e) => update('basic', e.target.value)} /></label><label>Allowances<input type="number" value={selected.allowances} min="0" onChange={(e) => update('allowances', e.target.value)} /></label><label>Deductions<input type="number" value={selected.deductions} min="0" onChange={(e) => update('deductions', e.target.value)} /></label><div className="net-preview"><span>Net salary</span><b>{money(selected.basic + selected.allowances - selected.deductions)}</b></div></section><SalarySlip salary={{ ...selected, month: 'August 2026' }} /></section></section></main>
}
