import { useCallback, useEffect, useState } from "react";
import api from "./api/axiosInstance";
import "./App.css";

const emptyEmployee = { name: "", email: "", password: "welcome123", phone: "", department: "", designation: "", joiningDate: "", salary: "" };
const messageOf = (error) => error.response?.data?.message || "Something went wrong. Please try again.";
const dateText = (date) => date ? new Date(date).toLocaleDateString() : "—";
const timeText = (date) => date ? new Date(date).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—";

function App() {
  const [user, setUser] = useState(null), [ready, setReady] = useState(false), [notice, setNotice] = useState(null);
  const flash = useCallback((type, text) => setNotice({ type, text }), []);
  useEffect(() => {
    (async () => {
      const token = localStorage.getItem("token");
      if (token) {
        try {
          setUser((await api.get("/auth/me")).data.user);
        } catch {
          localStorage.removeItem("token");
        }
      }
      setReady(true);
    })();
  }, []);
  const logout = async () => { try { await api.post("/auth/logout"); } catch {} localStorage.removeItem("token"); setUser(null); flash("success", "You have been logged out."); };
  if (!ready) return <div className="message-page"><p>Restoring your session…</p></div>;
  return user ? <Portal user={user} setUser={setUser} logout={logout} notice={notice} dismiss={() => setNotice(null)} flash={flash} /> : <Auth onAuthenticated={setUser} flash={flash} />;
}

function Auth({ onAuthenticated, flash }) {
  const [signup, setSignup] = useState(false), [form, setForm] = useState({ name: "", email: "", password: "" }), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const submit = async (event) => { event.preventDefault(); setError(""); if (signup && !form.name.trim()) return setError("Your name is required."); if (!/^\S+@\S+\.\S+$/.test(form.email) || form.password.length < 6) return setError("Enter a valid email and a password of at least 6 characters."); setBusy(true); try { const { data } = await api.post(signup ? "/auth/signup" : "/auth/login", form); localStorage.setItem("token", data.token); onAuthenticated(data.user); flash("success", `Welcome${signup ? " aboard" : " back"}, ${data.user.name}.`); } catch (err) { setError(messageOf(err)); } finally { setBusy(false); } };
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow">HRMS PORTAL</p><h1>{signup ? "Create your account" : "Welcome back"}</h1><p className="muted">{signup ? "Create an employee account to get started." : "Sign in to continue to your workspace."}</p>{signup && <Field label="Full name" value={form.name} onChange={(name) => setForm({ ...form, name })} />}<Field label="Email" type="email" value={form.email} onChange={(email) => setForm({ ...form, email })} /><Field label="Password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} />{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? "Please wait…" : signup ? "Create account" : "Sign in"}</button><button className="link-button" type="button" onClick={() => { setSignup(!signup); setError(""); }}>{signup ? "Already have an account? Sign in" : "Need an account? Register"}</button></form></main>;
}

function Portal({ user, setUser, logout, notice, dismiss, flash }) {
  const admin = user.role === "ADMIN", [view, setView] = useState(admin ? "dashboard" : "my-work");
  const items = admin ? [["dashboard", "Dashboard"], ["employees", "Employees"], ["leaves", "Leave requests"], ["attendance", "Attendance"]] : [["my-work", "My workspace"], ["my-leaves", "My leave requests"], ["my-attendance", "My attendance"]];
  return <div className="portal"><aside><div className="brand">PEOPLEFLOW</div><p className="role-label">{admin ? "ADMIN CONSOLE" : "EMPLOYEE PORTAL"}</p><nav>{items.map(([key, label]) => <button className={view === key ? "active" : ""} key={key} onClick={() => setView(key)}>{label}</button>)}</nav><button className="logout" onClick={logout}>Log out</button></aside><main className="content"><header><div><h1>{items.find(([key]) => key === view)?.[1]}</h1><p className="muted">Manage your people operations in one place.</p></div><div className="account"><strong>{user.name}</strong><span>{user.email}</span></div></header>{notice && <div className={`notice ${notice.type}`} role="alert">{notice.text}<button onClick={dismiss}>×</button></div>}{admin ? <AdminView view={view} flash={flash} /> : <EmployeeView view={view} user={user} setUser={setUser} flash={flash} />}</main></div>;
}
function AdminView({ view, flash }) { return view === "employees" ? <Employees flash={flash} /> : view === "leaves" ? <Leaves admin flash={flash} /> : view === "attendance" ? <Attendance flash={flash} /> : <Dashboard />; }
function EmployeeView({ view, user, setUser, flash }) { return view === "my-leaves" ? <Leaves flash={flash} /> : view === "my-attendance" ? <MyAttendance user={user} flash={flash} /> : <MyWork user={user} setUser={setUser} flash={flash} />; }
function Dashboard() { const [data, setData] = useState(null), [error, setError] = useState(""); useEffect(() => { api.get("/admin/dashboard").then((r) => setData(r.data.data)).catch((e) => setError(messageOf(e))); }, []); if (error) return <State error={error} />; if (!data) return <State />; return <><div className="metric-grid">{[["Active employees", data.totalEmployees], ["Present today", data.presentToday], ["On leave", data.onLeave], ["Pending requests", data.pendingLeaves]].map(([label, value]) => <div className="metric-card" key={label}><p>{label}</p><strong>{value}</strong></div>)}</div><section className="panel"><h2>Recent leave activity</h2><Table headers={["Employee", "Activity", "Status", "Updated"]} rows={data.recentActivities.map((item) => [item.employee, item.activity, <Badge key={item.id} value={item.status} />, dateText(item.createdAt)])} empty="No recent leave activity." /></section></>; }
function Employees({ flash }) { const [employees, setEmployees] = useState([]), [search, setSearch] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState(""), [editing, setEditing] = useState(null); const load = useCallback(async (term = search) => { setLoading(true); try { setEmployees((await api.get("/employees", { params: { search: term } })).data.employees); setError(""); } catch (e) { setError(messageOf(e)); } finally { setLoading(false); } }, [search]); useEffect(() => { load(""); }, []); const deactivate = async (employee) => { if (!window.confirm(`Deactivate ${employee.name}? They will no longer be able to sign in.`)) return; try { await api.delete(`/employees/${employee._id}`); flash("success", `${employee.name} was deactivated.`); load(); } catch (e) { flash("error", messageOf(e)); } }; return <><div className="toolbar"><input aria-label="Search employees" placeholder="Search name, email, department…" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} /><button onClick={() => load()}>Search</button><button onClick={() => setEditing(emptyEmployee)}>Add employee</button></div>{error ? <State error={error} /> : loading ? <State /> : <section className="panel"><Table headers={["Name", "Department", "Designation", "Status", "Actions"]} empty="No employees match your search." rows={employees.map((employee) => [<span key={employee._id}><strong>{employee.name}</strong><small>{employee.email}</small></span>, employee.department || "—", employee.designation || "—", <Badge key={`s${employee._id}`} value={employee.status} />, <span className="row-actions" key={`a${employee._id}`}><button onClick={() => setEditing(employee)}>Edit</button>{employee.status === "ACTIVE" && <button className="danger-button" onClick={() => deactivate(employee)}>Deactivate</button>}</span>])} /></section>}{editing && <EmployeeForm employee={editing} close={() => setEditing(null)} saved={() => { setEditing(null); load(); }} flash={flash} />}</>; }
function EmployeeForm({ employee, close, saved, flash }) { const [form, setForm] = useState({ ...emptyEmployee, ...employee, joiningDate: employee.joiningDate ? employee.joiningDate.slice(0, 10) : "" }), [busy, setBusy] = useState(false), [error, setError] = useState(""); const edit = Boolean(employee._id); const submit = async (event) => { event.preventDefault(); if (!form.name.trim() || !/^\S+@\S+\.\S+$/.test(form.email)) return setError("Name and a valid email are required."); if (!edit && form.password.length < 6) return setError("The temporary password must be at least 6 characters."); setBusy(true); try { const body = { ...form, salary: Number(form.salary || 0) }; if (edit) { delete body.email; delete body.password; await api.put(`/employees/${employee._id}`, body); } else await api.post("/employees", body); flash("success", `Employee ${edit ? "updated" : "created"} successfully.`); saved(); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-title"><h2>{edit ? "Edit employee" : "Add employee"}</h2><button type="button" className="icon-button" onClick={close}>×</button></div><div className="form-grid"><Field label="Full name" value={form.name} onChange={(name) => setForm({ ...form, name })} /><Field label="Email" type="email" disabled={edit} value={form.email} onChange={(email) => setForm({ ...form, email })} />{!edit && <Field label="Temporary password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} />}<Field label="Phone" value={form.phone} onChange={(phone) => setForm({ ...form, phone })} /><Field label="Department" value={form.department} onChange={(department) => setForm({ ...form, department })} /><Field label="Designation" value={form.designation} onChange={(designation) => setForm({ ...form, designation })} /><Field label="Joining date" type="date" value={form.joiningDate} onChange={(joiningDate) => setForm({ ...form, joiningDate })} /><Field label="Salary" type="number" min="0" value={form.salary} onChange={(salary) => setForm({ ...form, salary })} /></div>{error && <p className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button disabled={busy}>{busy ? "Saving…" : "Save employee"}</button></div></form></div>; }
function Leaves({ admin, flash }) { const [leaves, setLeaves] = useState([]), [filter, setFilter] = useState(""), [loading, setLoading] = useState(true), [showForm, setShowForm] = useState(false); const load = useCallback(async () => { setLoading(true); try { setLeaves((await api.get("/leaves", { params: filter ? { status: filter } : {} })).data.leaves); } catch (e) { flash("error", messageOf(e)); } finally { setLoading(false); } }, [filter]); useEffect(() => { load(); }, [load]); const review = async (id, action) => { try { await api.put(`/leaves/${id}/${action}`); flash("success", `Leave ${action}d.`); load(); } catch (e) { flash("error", messageOf(e)); } }; return <><div className="toolbar"><select aria-label="Filter leave status" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">All statuses</option><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select>{!admin && <button onClick={() => setShowForm(true)}>Apply for leave</button>}</div>{loading ? <State /> : <section className="panel"><Table headers={admin ? ["Employee", "Type", "Dates", "Reason", "Status", "Review"] : ["Type", "Dates", "Reason", "Status"]} empty="No leave requests found." rows={leaves.map((leave) => { const common = [leave.leaveType, `${dateText(leave.fromDate)} – ${dateText(leave.toDate)}`, leave.reason, <Badge key={leave._id} value={leave.status} />]; return admin ? [leave.employeeId?.name || "Employee", ...common, leave.status === "PENDING" ? <span className="row-actions" key={`r${leave._id}`}><button onClick={() => review(leave._id, "approve")}>Approve</button><button className="danger-button" onClick={() => review(leave._id, "reject")}>Reject</button></span> : "—"] : common; })} /></section>}{showForm && <LeaveForm close={() => setShowForm(false)} saved={() => { setShowForm(false); load(); }} flash={flash} />}</>; }
function LeaveForm({ close, saved, flash }) { const [form, setForm] = useState({ leaveType: "ANNUAL", fromDate: "", toDate: "", reason: "" }), [error, setError] = useState(""), [busy, setBusy] = useState(false); const submit = async (event) => { event.preventDefault(); if (!form.fromDate || !form.toDate || !form.reason.trim()) return setError("Complete all leave details."); if (form.fromDate > form.toDate) return setError("The start date cannot be after the end date."); setBusy(true); try { await api.post("/leaves", form); flash("success", "Leave request submitted."); saved(); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } }; return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-title"><h2>Apply for leave</h2><button type="button" className="icon-button" onClick={close}>×</button></div><Field label="Leave type" as="select" value={form.leaveType} onChange={(leaveType) => setForm({ ...form, leaveType })} options={["ANNUAL", "SICK", "PERSONAL", "UNPAID"]} /><Field label="From date" type="date" value={form.fromDate} onChange={(fromDate) => setForm({ ...form, fromDate })} /><Field label="To date" type="date" value={form.toDate} onChange={(toDate) => setForm({ ...form, toDate })} /><Field label="Reason" as="textarea" value={form.reason} onChange={(reason) => setForm({ ...form, reason })} />{error && <p className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button disabled={busy}>{busy ? "Submitting…" : "Submit request"}</button></div></form></div>; }
function Attendance({ flash }) { const today = new Date().toISOString().slice(0, 10), [date, setDate] = useState(today), [status, setStatus] = useState(""), [rows, setRows] = useState([]), [summary, setSummary] = useState({}), [loading, setLoading] = useState(true), [error, setError] = useState(""); const load = useCallback(async () => { setLoading(true); try { const endpoint = date === today ? "/attendance/today" : "/attendance"; const [list, totals] = await Promise.all([api.get(endpoint, { params: endpoint === "/attendance" ? { date, status } : {} }), api.get("/attendance/summary", { params: { from: date, to: date } })]); setRows(list.data.attendance.filter((row) => !status || row.status === status)); setSummary(totals.data.summary); setError(""); } catch (e) { setError(messageOf(e)); flash("error", messageOf(e)); } finally { setLoading(false); } }, [date, status]); useEffect(() => { load(); }, [load]); return <><div className="metric-grid small">{[["Present", summary.PRESENT || 0], ["Absent", date === today ? rows.filter((r) => r.status === "ABSENT").length : summary.ABSENT || 0], ["Half day", summary.HALF_DAY || 0], ["On leave", summary.LEAVE || 0]].map(([label, value]) => <div className="metric-card" key={label}><p>{label}</p><strong>{value}</strong></div>)}</div><div className="toolbar"><input aria-label="Attendance date" type="date" value={date} onChange={(e) => setDate(e.target.value)} /><select aria-label="Filter attendance" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option>PRESENT</option><option>ABSENT</option><option>HALF_DAY</option><option>LEAVE</option></select></div>{error ? <State error={error} /> : loading ? <State /> : <section className="panel"><Table headers={["Employee", "Department", "Status", "Check in", "Check out"]} empty="No attendance records for this date." rows={rows.map((row) => [row.employeeId?.name || "Employee", row.employeeId?.department || "—", <Badge key={row._id} value={row.status} />, timeText(row.checkIn), timeText(row.checkOut)])} /></section>}</>; }
function MyWork({ user, setUser, flash }) { const [phone, setPhone] = useState(user.phone || ""), [saving, setSaving] = useState(false); const save = async (e) => { e.preventDefault(); setSaving(true); try { setUser((await api.patch("/profile", { phone })).data.user); flash("success", "Profile updated."); } catch (err) { flash("error", messageOf(err)); } finally { setSaving(false); } }; return <><div className="metric-grid small"><div className="metric-card"><p>Department</p><strong className="text-value">{user.department || "Not assigned"}</strong></div><div className="metric-card"><p>Designation</p><strong className="text-value">{user.designation || "Not assigned"}</strong></div></div><section className="panel profile-panel"><h2>My profile</h2><p><strong>{user.name}</strong><br />{user.email}<br />Joined {dateText(user.joiningDate)}</p><form onSubmit={save}><Field label="Phone" value={phone} onChange={setPhone} /><button disabled={saving}>{saving ? "Saving…" : "Update contact number"}</button></form></section></>; }
function MyAttendance({ user, flash }) { const [records, setRecords] = useState(null); const load = useCallback(() => api.get(`/attendance/${user._id}`).then((r) => setRecords(r.data.attendance)).catch((e) => { setRecords([]); flash("error", messageOf(e)); }), [user._id]); useEffect(() => { load(); }, [load]); const check = async (action) => { try { await api.post(`/attendance/${action}`); load(); } catch (e) { flash("error", messageOf(e)); } }; if (!records) return <State />; const today = new Date().toDateString(), record = records.find((item) => new Date(item.date).toDateString() === today); return <><section className="panel"><h2>Today</h2><p>Status: <Badge value={record?.status || "NOT MARKED"} /></p><p>Check in: {timeText(record?.checkIn)} · Check out: {timeText(record?.checkOut)}</p><div className="row-actions"><button disabled={Boolean(record?.checkIn)} onClick={() => check("check-in")}>Check in</button><button disabled={!record?.checkIn || Boolean(record?.checkOut)} onClick={() => check("check-out")}>Check out</button></div></section><section className="panel"><h2>Attendance history</h2><Table headers={["Date", "Status", "Check in", "Check out"]} rows={records.map((r) => [dateText(r.date), <Badge key={r._id} value={r.status} />, timeText(r.checkIn), timeText(r.checkOut)])} empty="No attendance yet." /></section></>; }
function Field({ label, value, onChange, type = "text", as, options, ...props }) { return <label>{label}{as === "select" ? <select value={value} onChange={(e) => onChange(e.target.value)} {...props}>{options.map((option) => <option key={option}>{option}</option>)}</select> : as === "textarea" ? <textarea value={value} onChange={(e) => onChange(e.target.value)} {...props} /> : <input type={type} value={value} onChange={(e) => onChange(e.target.value)} {...props} />}</label>; }
function Badge({ value }) { return <span className={`badge ${String(value).toLowerCase().replace(/_/g, "-")}`}>{String(value).replace(/_/g, " ")}</span>; }
function Table({ headers, rows, empty }) { return <div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="empty-state">{empty}</td></tr>}</tbody></table></div>; }
function State({ error }) { return <div className={`dashboard-state ${error ? "state-error" : ""}`}>{error || "Loading…"}</div>; }
export default App;