import { createContext, useContext, useEffect, useState } from 'react'
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { api } from './api'
import './App.css'

const AuthContext = createContext(null)
const adminLinks = [['dashboard', 'Dashboard'], ['employees', 'User management'], ['attendance', 'Attendance'], ['leaves', 'Leave requests'], ['reports', 'Reports']]
const employeeLinks = [['dashboard', 'My dashboard'], ['profile', 'My profile'], ['attendance', 'Attendance'], ['apply-leave', 'Apply leave'], ['leaves', 'Leave status']]
const dashboardFor = (role) => role === 'ADMIN' ? '/admin/dashboard' : '/employee/dashboard'
const useAuth = () => useContext(AuthContext)

function AuthProvider({ children }) {
  const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem('hrms_user')) } catch { return null } })
  const [checking, setChecking] = useState(Boolean(localStorage.getItem('hrms_token')))
  useEffect(() => { if (!localStorage.getItem('hrms_token')) return setChecking(false); api('/api/auth/me').then(({ user }) => { setUser(user); localStorage.setItem('hrms_user', JSON.stringify(user)) }).catch(() => { localStorage.removeItem('hrms_token'); localStorage.removeItem('hrms_user'); setUser(null) }).finally(() => setChecking(false)) }, [])
  const login = (data) => { localStorage.setItem('hrms_token', data.token); localStorage.setItem('hrms_user', JSON.stringify(data.user)); setUser(data.user) }
  const logout = async () => { try { await api('/api/auth/logout', { method: 'POST' }) } catch {} localStorage.removeItem('hrms_token'); localStorage.removeItem('hrms_user'); setUser(null) }
  return <AuthContext.Provider value={{ user, checking, login, logout }}>{children}</AuthContext.Provider>
}

function PublicNav() { const { user } = useAuth(); return <header className="public-nav"><Link className="brand" to="/">HRMS</Link><nav><a href="#features">Features</a><a href="#about">About</a>{user ? <Link className="nav-cta" to={dashboardFor(user.role)}>Workspace</Link> : <><Link to="/login">Log in</Link><Link className="nav-cta" to="/signup">Get started</Link></>}</nav></header> }
function Home() { const features = [['Employee directory', 'Keep every employee profile accurate and easy to find.'], ['Leave management', 'Review requests and give your people clarity fast.'], ['Attendance tracking', 'Record check-ins, check-outs and daily presence.'], ['Admin insights', 'See workforce totals and pending work at a glance.']]; return <><PublicNav /><main className="landing"><section className="hero"><div><p className="eyebrow">PEOPLE OPERATIONS, SIMPLIFIED</p><h1>Your team, working in sync.</h1><p>HRMS brings employee records, attendance, leave and meaningful workforce insights into one calm, reliable workspace.</p><div className="hero-actions"><Link className="button-link" to="/signup">Create an account</Link><a className="text-link" href="#features">Explore features →</a></div></div><div className="hero-card"><span>Today at a glance</span><strong>24</strong><p>team members present</p><div className="mini-bars"><i /><i /><i /><i /></div></div></section><section id="features" className="features"><p className="eyebrow">EVERYTHING IN ONE PLACE</p><h2>Built for the rhythm of work</h2><div className="feature-grid">{features.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section id="about" className="landing-cta"><div><h2>A better home for people operations.</h2><p>Secure role-based access keeps every team member focused on what matters.</p></div><Link className="button-link" to="/signup">Start using HRMS</Link></section></main><footer><span>© 2026 HRMS</span><span>Built for better workdays.</span></footer></> }
function AuthPage({ mode }) { const { user, login } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'EMPLOYEE' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); if (user) return <Navigate to={dashboardFor(user.role)} replace />; const submit = async (e) => { e.preventDefault(); setError(''); if (mode === 'signup' && form.name.trim().length < 2) return setError('Please enter your full name.'); if (form.password.length < 6) return setError('Password must be at least 6 characters.'); setBusy(true); try { const data = await api(`/api/auth/${mode === 'login' ? 'login' : 'signup'}`, { method: 'POST', body: JSON.stringify(form) }); login(data); navigate(dashboardFor(data.user.role), { replace: true }) } catch (err) { setError(err.message) } finally { setBusy(false) } }; return <main className="auth-page"><section className="auth-card"><Link className="auth-brand" to="/">HRMS</Link><p className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'GET STARTED'}</p><h1>{mode === 'login' ? 'Sign in to your workspace' : 'Create your HRMS account'}</h1><form onSubmit={submit} noValidate>{mode === 'signup' && <label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label>}<label>Email address<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" minLength="6" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label>{mode === 'signup' && <label>Account type<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="EMPLOYEE">Employee</option><option value="ADMIN">Admin / HR</option></select></label>}{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Create account'}</button></form><p className="auth-switch">{mode === 'login' ? 'New here? ' : 'Already have an account? '}<Link to={mode === 'login' ? '/signup' : '/login'}>{mode === 'login' ? 'Create an account' : 'Log in'}</Link></p></section></main> }
function Protected({ role, children }) { const { user, checking } = useAuth(); if (checking) return <main className="message-page">Checking your session…</main>; if (!user) return <Navigate to="/login" replace />; if (user.role !== role) return <Navigate to="/unauthorized" replace />; return children }
function Dashboard() { const [data, setData] = useState(null); const [error, setError] = useState(''); const load = () => { setError(''); api('/api/admin/dashboard').then(({ data }) => setData(data)).catch((e) => setError(e.message)) }; useEffect(load, []); if (error) return <section className="dashboard-state">{error}<button onClick={load}>Retry</button></section>; if (!data) return <section className="dashboard-state">Loading dashboard…</section>; return <><section className="metric-grid">{[['Total employees', data.totalEmployees], ['Present today', data.presentToday], ['On leave', data.onLeave], ['Pending requests', data.pendingLeaves]].map(([label, value]) => <article className="metric-card" key={label}><p>{label}</p><strong>{value ?? 0}</strong></article>)}</section><section className="dashboard-grid"><article className="panel"><h2>Payroll summary</h2><div className="payroll-row"><span>Total payroll</span><strong>{data.payrollSummary?.total ?? 0}</strong></div><div className="payroll-row"><span>Employees processed</span><strong>{data.payrollSummary?.processedEmployees ?? 0}</strong></div><p className="panel-note">Payroll data will appear once processed.</p></article><article className="panel"><h2>Recent activity</h2>{data.recentActivities?.length ? <div className="table-wrap"><table><thead><tr><th>Activity</th><th>Employee</th><th>Date</th><th>Status</th></tr></thead><tbody>{data.recentActivities.map((item) => <tr key={item.id}><td>{item.activity}</td><td>{item.employee}</td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td><span className="status">{item.status}</span></td></tr>)}</tbody></table></div> : <p className="empty-state">No recent activities</p>}</article></section></> }
function Employees() { const [employees, setEmployees] = useState([]); const [error, setError] = useState(''); const [search, setSearch] = useState(''); useEffect(() => { api(`/api/employees${search ? `?search=${encodeURIComponent(search)}` : ''}`).then(({ employees }) => setEmployees(employees)).catch((e) => setError(e.message)) }, [search]); return <section className="panel page-panel"><div className="panel-heading"><div><h2>Employee directory</h2><p>Manage your workforce records.</p></div><input aria-label="Search employees" placeholder="Search employees" value={search} onChange={(e) => setSearch(e.target.value)} /></div>{error ? <p className="error">{error}</p> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Department</th><th>Designation</th><th>Status</th></tr></thead><tbody>{employees.map((person) => <tr key={person._id}><td><strong>{person.name}</strong><br /><small>{person.email}</small></td><td>{person.department || '—'}</td><td>{person.designation || '—'}</td><td><span className="status">{person.status}</span></td></tr>)}{!employees.length && <tr><td colSpan="4" className="empty-state">No employees found.</td></tr>}</tbody></table></div>}</section> }
function Placeholder({ title }) { return <section className="placeholder"><h2>{title}</h2><p>This protected module is connected to the role-aware workspace and ready for its workflow implementation.</p></section> }
function Portal() { const { user, logout } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const isAdmin = user.role === 'ADMIN'; const links = isAdmin ? adminLinks : employeeLinks; const title = links.find(([path]) => location.pathname.endsWith(path))?.[1] || 'Workspace'; const leave = async () => { await logout(); navigate('/login', { replace: true }) }; return <div className="portal"><aside><Link className="brand" to={dashboardFor(user.role)}>HRMS</Link><p className="role-label">{isAdmin ? 'ADMIN / HR' : 'EMPLOYEE'}</p><nav>{links.map(([path, label]) => <NavLink key={path} to={path}>{label}</NavLink>)}</nav><button className="logout" onClick={leave}>Log out</button></aside><main className="content"><header><div><p className="eyebrow">{isAdmin ? 'ADMINISTRATION' : 'MY WORKSPACE'}</p><h1>{title}</h1></div><div className="account"><strong>{user.name}</strong><span>{user.email}</span></div></header><Routes><Route path="dashboard" element={isAdmin ? <Dashboard /> : <Placeholder title="My dashboard" />} />{isAdmin && <Route path="employees" element={<Employees />} />}{links.filter(([path]) => path !== 'dashboard' && !(isAdmin && path === 'employees')).map(([path, label]) => <Route key={path} path={path} element={<Placeholder title={label} />} />)}</Routes></main></div> }
function App() { return <BrowserRouter><AuthProvider><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/signup" element={<AuthPage mode="signup" />} /><Route path="/unauthorized" element={<main className="message-page"><div><h1>Unauthorized</h1><p>You don’t have access to this area.</p><Link className="button-link" to="/">Return home</Link></div></main>} /><Route path="/admin/*" element={<Protected role="ADMIN"><Portal /></Protected>} /><Route path="/employee/*" element={<Protected role="EMPLOYEE"><Portal /></Protected>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></AuthProvider></BrowserRouter> }
export default App
